### PR TITLE
Baseclass

### PR DESCRIPTION
**Pull request by shubhamjain0594**
- Added baseclass
- Added population density function
- Added testing scripts.

### CODE REVIEW

**Comment by aoehmichen** [comment]
Overwhole looks good but please remove Author from the headers in the files. (leave the one in setup.py)
It would be best if the CI was green and just to avoid any surprise if you could test against python3.6 as well it would be great (though not mandatory)

If you want you can reference the OPAL project website in the readme. 

I will merge as soon as the two first two have been fixed.

**Comment by shubhamjain0594** [comment]
Hi @aoehmichen ,
- Authors have been removed.
- All green in CI

Python 3.6 compatibility needs to be checked.

**Comment by shubhamjain0594** [comment]
Python 3.6 integration done.

**Comment by shubhamjain0594** [comment]
README has been updated with all the required instructions.

**Pull request merged**
